### ISSUE TITLE
CI

### ISSUE THREAD

**Issue by begarco** [WatchDogZZ/docs#13]
Même la CI arrive pas à compiler le rapport sans erreur (et c'est même pas les mêmes que moi), si t'as le temps de jeter un oeil.

**Comment by BBS007** [comment]
Franchement de la CI pour compiler un rapport ...
Moi ca compile bien donc je vais pas regarder. J'ai aucune erreur.
Ca doit encore être de la config ou un package qui foire

**Comment by begarco** [comment]
Ben ça aiderait pas mal si on pouvait déterminer où ça foire genre pour faire le rapport. Je vais regarder
