### ISSUE TITLE
Résumé

### ISSUE THREAD

**Issue by BBS007** [WatchDogZZ/docs#3]
J'ai commencé le résumé en Français.
Regarde ce qui est bon et corrige ce qui ne va pas.
Lorsque ce sera bon, fais moi signe et je traduirai en Anglais.

**Comment by begarco** [comment]
lol mais pourquoi tu réutilise pas l'abstract d'anglais ?

**Comment by BBS007** [comment]
Parce que je ne pense pas qu'il soit adapté au rapport ...

**Comment by begarco** [comment]
Ben il est sensé pourtant ...

**Comment by BBS007** [comment]
Bah écoute, si tu veux on prend l'anglais ...

**Comment by begarco** [comment]
SI tu veux faire quelque chose de mieux je suis pas contre mais pourquoi tu ne l'as pas fait avant ? #ForSuzan

**Comment by BBS007** [comment]
Parce qu'il y avait des consignes particulières
#300Words
#4Parts

**Comment by BBS007** [comment]
Il faudrait que tu le lises pour que je traduise si ok

**Comment by begarco** [comment]
Fait, j'ai modifié.

Par contre on écrit "service web" il me semble et pas "Service Web".

**Comment by begarco** [comment]
Ils n'apparaissent pas sur le pdf ....

**Comment by BBS007** [comment]
CRLF -> LF
