### ISSUE TITLE
Pas de paragraphes dans l'intro

### ISSUE THREAD

**Issue by begarco** [WatchDogZZ/docs#9]

**Comment by BBS007** [comment]
C'est à dire ? Je ne comprends pas

**Comment by begarco** [comment]
Dans le fichier tex il y a des paragraphes mais dans le main.pdf c'est juste un seul pavé

**Comment by BBS007** [comment]
Moi c'est comme il faut
![capture](https://cloud.githubusercontent.com/assets/3964808/23212189/e010ce5e-f905-11e6-9e45-bb097fbbf443.PNG)

**Comment by begarco** [comment]
Bon ça doit venir aussi de mon erreur de compil'
